### ISSUE TITLE
[Bug] the new `elasticstack_kibana_alerting_rule` resource

### ISSUE THREAD

**Issue by jsangilve** [elastic/terraform-provider-elasticstack#298]
**Describe the bug**
The `elasticstack_kibana_alerting_rule` fails when executing `terraform apply` with _The plugin encountered an error, and failed to respond to the plugin_

**To Reproduce**
1. **I built the plugin locally** to be able to use the new `elasticstack_kibana_alerting_rule` resource
2. I defined the following alert:
```terraform
resource "elasticstack_kibana_alerting_rule" "tf-test-alert" {
  name         = "tf - service-x - apm - error count threshold exceeded"
  consumer     = "alerts"
  notify_when  = "onActiveAlert"
  rule_type_id = "apm.error_rate"
  interval     = "5m"
  enabled      = false
  #   tags         = tolist(["tag1", "tag2"])

  params = jsonencode({
    threshold   = 2
    windowSize  = 5
    windowUnit  = "m"
    environment = "prod"
    serviceName = "service-x"
  })

  actions {
    id    = local.connector_id (just the id of an existing connector)
    group = "threshold_met"
    params = jsonencode({
      "body" : {
        "message" : "APM service error count threshold exceeded",
        "priority" : "P1"
      }
    })
  }
}
```
3. TF operations to execute to get the error `terraform apply`. The plan is successfully output
3. See the error in the output:

```
  + resource "elasticstack_kibana_alerting_rule" "tf-test-alert" {
      + consumer              = "alerts"
      + enabled               = false
      + id                    = (known after apply)
      + interval              = "5m"
      + last_execution_date   = (known after apply)
      + last_execution_status = (known after apply)
      + name                  = "tf - service-x - apm - error count threshold exceeded"
      + notify_when           = "onActiveAlert"
      + params                = jsonencode(
            {
              + environment = "prod"
              + serviceName = "service-x"
              + threshold   = 2
              + windowSize  = 5
              + windowUnit  = "m"
            }
        )
      + rule_id               = (known after apply)
      + rule_type_id          = "apm.error_rate"
      + scheduled_task_id     = (known after apply)
      + space_id              = "default"

      + actions {
          + group  = "threshold_met"
          + id     = "32406c0-ae9b-11ed-9d01-57f382eb81ef"
          + params = jsonencode(
                {
                  + body = {
                      + message = "APM service error count threshold exceeded"
                    }
                }
            )
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
╷
│ Warning: v1alpha1 of the client authentication API is deprecated, use v1beta1 or above
│
│   with provider["registry.terraform.io/hashicorp/kubernetes"],
│   on versions.tf line 64, in provider "kubernetes":
│   64:     api_version = "client.authentication.k8s.io/v1alpha1"
│
│ v1alpha1 of the client authentication API will be removed in Kubernetes client versions 1.24 and above. You may need to update your exec plugin to use the latest version.
╵

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

elasticstack_kibana_alerting_rule.tf-test-alert: Creating...
╷
│ Error: Plugin did not respond
│
│   with elasticstack_kibana_alerting_rule.tf-test-alert,
│   on ec-kibana-alerting-rules.tf line 7, in resource "elasticstack_kibana_alerting_rule" "tf-test-alert":
│    7: resource "elasticstack_kibana_alerting_rule" "tf-test-alert" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-elasticstack plugin:

panic: interface conversion: interface {} is []interface {}, not string

goroutine 13 [running]:
github.com/elastic/terraform-provider-elasticstack/internal/kibana.getAlertingRuleFromResourceData(0x1?)
        /Users/jsangil/projects/terraform-provider-elasticstack/internal/kibana/alerting.go:181 +0x7d4
github.com/elastic/terraform-provider-elasticstack/internal/kibana.resourceRuleCreate({0x1fddfe8, 0xc000381500}, 0x0?, {0x1d5ba80, 0xc0002645a0})
        /Users/jsangil/projects/terraform-provider-elasticstack/internal/kibana/alerting.go:200 +0xc9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0004c3a40, {0x1fde020, 0xc000544ea0}, 0xd?, {0x1d5ba80, 0xc0002645a0})
        /Users/jsangil/.asdf/installs/golang/1.19.7/packages/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0004c3a40, {0x1fde020, 0xc000544ea0}, 0xc00078d040, 0xc000540880, {0x1d5ba80, 0xc0002645a0})
        /Users/jsangil/.asdf/installs/golang/1.19.7/packages/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0001220a8, {0x1fde020?, 0xc000544d80?}, 0xc0003a9450)
        /Users/jsangil/.asdf/installs/golang/1.19.7/packages/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc00049f4d0, 0xc00049f530, {0xc0005101a0, 0x1, 0x1}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        /Users/jsangil/.asdf/installs/golang/1.19.7/packages/pkg/mod/github.com/hashicorp/terraform-plugin-mux@v0.9.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00012ad20, {0x1fde020?, 0xc000544060?}, 0xc0000f7a40)
        /Users/jsangil/.asdf/installs/golang/1.19.7/packages/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1dc1400?, 0xc00012ad20}, {0x1fde020, 0xc000544060}, 0xc0000f79d0, 0x0)
        /Users/jsangil/.asdf/installs/golang/1.19.7/packages/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000150000, {0x1fe1e80, 0xc0006024e0}, 0xc0005127e0, 0xc0004eae70, 0x2865160, 0x0)
        /Users/jsangil/.asdf/installs/golang/1.19.7/packages/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc000150000, {0x1fe1e80, 0xc0006024e0}, 0xc0005127e0, 0x0)
        /Users/jsangil/.asdf/installs/golang/1.19.7/packages/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /Users/jsangil/.asdf/installs/golang/1.19.7/packages/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /Users/jsangil/.asdf/installs/golang/1.19.7/packages/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

```

**Important**

❗ Please notice that the alert does actually get created if I remove the `tags` and `actions` fields. Basically, if you try an alert using the example provided in the docs, it works but as soon as you add `tags` or `actions` list/block, it fails.

**Expected behavior**
The Kibana alerting rule gets created

**Versions (please complete the following information):**
 - OS: MacOS
 - Terraform Version 1.2.8
 - Provider version `main` branch (unreleased)
 - Elasticsearch Version 8.0.1

**Comment by tobio** [comment]
Thanks for the report, sorry about this.

**Comment by jsangilve** [comment]
@tobio thank you, I'll try it out
