### ISSUE TITLE
[Bug] Provisioning a data view

### ISSUE THREAD

**Issue by Anri-Lombard** [elastic/terraform-provider-elasticstack#536]
**Describe the bug**
Provisioning a simple data view does not work

**To Reproduce**
1. TF configuration used:
```
terraform {
  required_version = ">= 1.0.0"
  required_providers {
    elasticstack = {
      source  = "elastic/elasticstack"
      version = "0.11.0"
    }
  }
}

module "kibana-dev" {
  source = "../modules/space-and-views"

  views = [
    {
      name            = "Data View QA Document Extractor V2 Metrics"
      time_field_name = "creationTime"
      title           = "qa-document-extractor-v2-metrics"
      space_id        = "default"
    }
  ]


}
```

Module used:
```
resource "elasticstack_kibana_data_view" "view" {
  for_each = { for idx, view in var.views : idx => view }

  data_view = {
    name            = each.value.name
    time_field_name = each.value.time_field_name
    title           = each.value.title
  }
  space_id = each.value.space_id
}
```

2. TF operations to execute to get the error `terraform apply`

For context here is the plan:
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.kibana-dev.elasticstack_kibana_data_view.view["0"] will be created
  + resource "elasticstack_kibana_data_view" "view" {
      + data_view = {
          + allow_no_index  = false
          + id              = (known after apply)
          + name            = "Data View QA Document Extractor V2 Metrics"
          + time_field_name = "creationTime"
          + title           = "qa-document-extractor-v2-metrics"
        }
      + id        = (known after apply)
      + override  = false
      + space_id  = "default"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

3. See the error in the output:
```
module.kibana-dev.elasticstack_kibana_data_view.view["0"]: Creating...
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-elasticstack_v0.11.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1cc2709]

goroutine 97 [running]:
github.com/elastic/terraform-provider-elasticstack/internal/kibana/data_view.(*Resource).Create(0xc0001cc018, {0x2293940, 0xc000724ff0}, {{{{0x2298658, 0xc00073f800}, {0x1f00200, 0xc00073e690}}, {0x229a2e8, 0xc000629b30}}, {{{0x2298658, ...}, ...}, ...}, ...}, ...)
        github.com/elastic/terraform-provider-elasticstack/internal/kibana/data_view/create.go:43 +0x8e9
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0xc000186f20, {0x2293940, 0xc000724ff0}, 0xc0006352b0, 0xc000635250)
        github.com/hashicorp/terraform-plugin-framework@v1.4.2/internal/fwserver/server_createresource.go:101 +0x578
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0xc000635408?, {0x2293940, 0xc000724ff0}, 0xc000114c80, 0xc000635408)
        github.com/hashicorp/terraform-plugin-framework@v1.4.2/internal/fwserver/server_applyresourcechange.go:57 +0x4a5
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0xc000186f20, {0x2293940?, 0xc000724ed0?}, 0xc000114b90)
        github.com/hashicorp/terraform-plugin-framework@v1.4.2/internal/proto6server/server_applyresourcechange.go:55 +0x3ff
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ApplyResourceChange(0x2293978?, {0x2293940?, 0xc000724bd0?}, 0xc000114b90)
        github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf6muxserver/mux_server_ApplyResourceChange.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc0002ade00, {0x2293940?, 0xc0007241b0?}, 0xc0003a8000)
        github.com/hashicorp/terraform-plugin-go@v0.19.1/tfprotov6/tf6server/server.go:857 +0x56a
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x2047ec0?, 0xc0002ade00}, {0x2293940, 0xc0007241b0}, 0xc0002bc200, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.19.1/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:467 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002381e0, {0x2293940, 0xc0007240f0}, {0x22992c0, 0xc000006ea0}, 0xc000726000, 0xc0003fdef0, 0x2d2f078, 0x0)
        google.golang.org/grpc@v1.59.0/server.go:1343 +0xe03
google.golang.org/grpc.(*Server).handleStream(0xc0002381e0, {0x22992c0, 0xc000006ea0}, 0xc000726000)
        google.golang.org/grpc@v1.59.0/server.go:1737 +0xc4c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.59.0/server.go:986 +0x86
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 5
        google.golang.org/grpc@v1.59.0/server.go:997 +0x145

Error: The terraform-provider-elasticstack_v0.11.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Expected behavior**
I expected a view to be created. Perhaps adding an example on the registry will also clear this up, but I can't see what error in my current config is causing this.

**Debug output**
Run `terraform` command with `TF_LOG=trace` and provide extended information on TF operations.

```
2024-01-24T11:19:02.624+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: POST /api/data_views/data_view HTTP/1.1
2024-01-24T11:19:02.624+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: Host: e7002f1200f24b5ab5343b51b6f6033e.europe-west1.gcp.cloud.es.io:9243
2024-01-24T11:19:02.624+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: User-Agent: elasticstack-terraform-provider/0.11.0
2024-01-24T11:19:02.624+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: Content-Length: 188
2024-01-24T11:19:02.624+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: Accept: application/json
2024-01-24T11:19:02.625+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: Authorization: Basic YW5yaS5sb21iYXJkQHNwcmludGhpdmUuY29tOkJFJCZDMmo1ajhCQGYlZFJUbw==
2024-01-24T11:19:02.625+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: Content-Type: application/json
2024-01-24T11:19:02.625+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: kbn-xsrf: true
2024-01-24T11:19:02.625+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: Accept-Encoding: gzip
2024-01-24T11:19:02.625+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0
2024-01-24T11:19:02.625+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: {"data_view":{"allowNoIndex":false,"id":"","name":"Data View QA Document Extractor V2 Metrics","timeFieldName":"creationTime","title":"qa-document-extractor-v2-metrics"},"override":false}
2024-01-24T11:19:02.625+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0
2024-01-24T11:19:03.264+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: 2024/01/24 11:19:03 
2024-01-24T11:19:03.264+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: HTTP/2.0 200 OK
2024-01-24T11:19:03.264+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: Content-Type: application/json; charset=UTF-8
2024-01-24T11:19:03.264+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: Date: Wed, 24 Jan 2024 09:19:05 GMT
2024-01-24T11:19:03.264+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: Warning: 299 Elasticsearch-7.17.13-2b211dbb8bfdecaf7f5b44d356bdfe54b1050c13 "[types removal] Specifying types in document index requests is deprecated, use the typeless endpoints instead (/{index}/_doc/{id}, /{index}/_doc, or /{index}/_create/{id})."
2024-01-24T11:19:03.264+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: X-Cloud-Request-Id: WXJuMVSNS9KeSSwj_x4jdg
2024-01-24T11:19:03.264+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: X-Elastic-Product: Elasticsearch
2024-01-24T11:19:03.264+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: X-Found-Handling-Cluster: e7002f1200f24b5ab5343b51b6f6033e
2024-01-24T11:19:03.264+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: X-Found-Handling-Instance: instance-0000000008
2024-01-24T11:19:03.264+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0
2024-01-24T11:19:03.264+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: {"_index":"api","_type":"data_views","_id":"data_view","_version":19,"result":"updated","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":18,"_primary_term":1}
2024-01-24T11:19:03.264+0200 [TRACE] provider.terraform-provider-elasticstack_v0.11.0: Served request: tf_provider_addr=registry.terraform.io/elastic/elasticstack @module=sdk.proto tf_proto_version=6.4 tf_req_id=3c29a8a0-86f8-9cff-2e41-81cdb3806721 tf_resource_type=elasticstack_kibana_data_view tf_rpc=ApplyResourceChange @caller=runtime/panic.go:914 timestamp="2024-01-24T11:19:03.264+0200"
2024-01-24T11:19:03.267+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: panic: runtime error: invalid memory address or nil pointer dereference
2024-01-24T11:19:03.267+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1cc2709]
2024-01-24T11:19:03.267+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0
2024-01-24T11:19:03.267+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: goroutine 9 [running]:
2024-01-24T11:19:03.267+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: github.com/elastic/terraform-provider-elasticstack/internal/kibana/data_view.(*Resource).Create(0xc0001d0088, {0x2293940, 0xc000225590}, {{{{0x2298658, 0xc000233da0}, {0x1f00200, 0xc000232c30}}, {0x229a2e8, 0xc00029f220}}, {{{0x2298658, ...}, ...}, ...}, ...}, ...)
2024-01-24T11:19:03.267+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0:  github.com/elastic/terraform-provider-elasticstack/internal/kibana/data_view/create.go:43 +0x8e9
2024-01-24T11:19:03.267+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0xc000186f20, {0x2293940, 0xc000225590}, 0xc0005472b0, 0xc000547250)
2024-01-24T11:19:03.267+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0:  github.com/hashicorp/terraform-plugin-framework@v1.4.2/internal/fwserver/server_createresource.go:101 +0x578
2024-01-24T11:19:03.267+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0xc000547408?, {0x2293940, 0xc000225590}, 0xc0006899f0, 0xc000547408)
2024-01-24T11:19:03.267+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0:  github.com/hashicorp/terraform-plugin-framework@v1.4.2/internal/fwserver/server_applyresourcechange.go:57 +0x4a5
2024-01-24T11:19:03.267+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0xc000186f20, {0x2293940?, 0xc000225470?}, 0xc000689950)
2024-01-24T11:19:03.267+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0:  github.com/hashicorp/terraform-plugin-framework@v1.4.2/internal/proto6server/server_applyresourcechange.go:55 +0x3ff
2024-01-24T11:19:03.267+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ApplyResourceChange(0x2293978?, {0x2293940?, 0xc000225170?}, 0xc000689950)
2024-01-24T11:19:03.267+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0:  github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf6muxserver/mux_server_ApplyResourceChange.go:36 +0x193
2024-01-24T11:19:03.267+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc0002adea0, {0x2293940?, 0xc000224780?}, 0xc0001faa80)
2024-01-24T11:19:03.267+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0:  github.com/hashicorp/terraform-plugin-go@v0.19.1/tfprotov6/tf6server/server.go:857 +0x56a
2024-01-24T11:19:03.267+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x2047ec0?, 0xc0002adea0}, {0x2293940, 0xc000224780}, 0xc0001a3100, 0x0)
2024-01-24T11:19:03.267+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0:  github.com/hashicorp/terraform-plugin-go@v0.19.1/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:467 +0x169
2024-01-24T11:19:03.267+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002381e0, {0x2293940, 0xc0002246c0}, {0x22992c0, 0xc000007520}, 0xc000223320, 0xc0003fdef0, 0x2d2f078, 0x0)
2024-01-24T11:19:03.267+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0:  google.golang.org/grpc@v1.59.0/server.go:1343 +0xe03
2024-01-24T11:19:03.267+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: google.golang.org/grpc.(*Server).handleStream(0xc0002381e0, {0x22992c0, 0xc000007520}, 0xc000223320)
2024-01-24T11:19:03.267+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0:  google.golang.org/grpc@v1.59.0/server.go:1737 +0xc4c
2024-01-24T11:19:03.268+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: google.golang.org/grpc.(*Server).serveStreams.func1.1()
2024-01-24T11:19:03.268+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0:  google.golang.org/grpc@v1.59.0/server.go:986 +0x86
2024-01-24T11:19:03.268+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 7
2024-01-24T11:19:03.268+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0:  google.golang.org/grpc@v1.59.0/server.go:997 +0x145
2024-01-24T11:19:03.270+0200 [ERROR] plugin6.(*GRPCProvider).ApplyResourceChange: error="rpc error: code = Unavailable desc = error reading from server: EOF"
2024-01-24T11:19:03.270+0200 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/elastic/elasticstack/0.11.0/darwin_amd64/terraform-provider-elasticstack_v0.11.0 pid=75406 error="exit status 2"
2024-01-24T11:19:03.270+0200 [TRACE] maybeTainted: module.kibana-dev.elasticstack_kibana_data_view.view["0"] encountered an error during creation, so it is now marked as tainted
2024-01-24T11:19:03.270+0200 [TRACE] GRPCProvider.v6: GetProviderSchema
2024-01-24T11:19:03.270+0200 [TRACE] GRPCProvider.v6: returning cached schema: EXTRA_VALUE_AT_END=registry.terraform.io/elastic/elasticstack
2024-01-24T11:19:03.270+0200 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState to workingState for module.kibana-dev.elasticstack_kibana_data_view.view["0"]
2024-01-24T11:19:03.270+0200 [TRACE] states.SyncState: pruning module.kibana-dev because it is empty
2024-01-24T11:19:03.270+0200 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState: removing state object for module.kibana-dev.elasticstack_kibana_data_view.view["0"]
2024-01-24T11:19:03.270+0200 [TRACE] evalApplyProvisioners: module.kibana-dev.elasticstack_kibana_data_view.view["0"] is tainted, so skipping provisioning
2024-01-24T11:19:03.270+0200 [TRACE] maybeTainted: module.kibana-dev.elasticstack_kibana_data_view.view["0"] was already tainted, so nothing to do
2024-01-24T11:19:03.270+0200 [TRACE] GRPCProvider.v6: GetProviderSchema
2024-01-24T11:19:03.270+0200 [TRACE] GRPCProvider.v6: returning cached schema: EXTRA_VALUE_AT_END=registry.terraform.io/elastic/elasticstack
2024-01-24T11:19:03.270+0200 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState to workingState for module.kibana-dev.elasticstack_kibana_data_view.view["0"]
2024-01-24T11:19:03.270+0200 [TRACE] states.SyncState: pruning module.kibana-dev because it is empty
2024-01-24T11:19:03.270+0200 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState: removing state object for module.kibana-dev.elasticstack_kibana_data_view.view["0"]
2024-01-24T11:19:03.270+0200 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2024-01-24T11:19:03.271+0200 [TRACE] statemgr.Filesystem: not making a backup, because the new snapshot is identical to the old
2024-01-24T11:19:03.271+0200 [TRACE] statemgr.Filesystem: no state changes since last snapshot
2024-01-24T11:19:03.271+0200 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2024-01-24T11:19:03.287+0200 [DEBUG] State storage *statemgr.Filesystem declined to persist a state snapshot
2024-01-24T11:19:03.287+0200 [ERROR] vertex "module.kibana-dev.elasticstack_kibana_data_view.view[\"0\"]" error: Plugin did not respond
2024-01-24T11:19:03.287+0200 [TRACE] vertex "module.kibana-dev.elasticstack_kibana_data_view.view[\"0\"]": visit complete, with errors
2024-01-24T11:19:03.287+0200 [TRACE] dag/walk: upstream of "module.kibana-dev (close)" errored, so skipping
2024-01-24T11:19:03.287+0200 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/elastic/elasticstack\"] (close)" errored, so skipping
2024-01-24T11:19:03.287+0200 [TRACE] dag/walk: upstream of "root" errored, so skipping
2024-01-24T11:19:03.288+0200 [TRACE] statemgr.Filesystem: not making a backup, because the new snapshot is identical to the old
2024-01-24T11:19:03.288+0200 [TRACE] statemgr.Filesystem: no state changes since last snapshot
2024-01-24T11:19:03.288+0200 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
2024-01-24T11:19:03.305+0200 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2024-01-24T11:19:03.305+0200 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock

Stack trace from the terraform-provider-elasticstack_v0.11.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1cc2709]

goroutine 9 [running]:
github.com/elastic/terraform-provider-elasticstack/internal/kibana/data_view.(*Resource).Create(0xc0001d0088, {0x2293940, 0xc000225590}, {{{{0x2298658, 0xc000233da0}, {0x1f00200, 0xc000232c30}}, {0x229a2e8, 0xc00029f220}}, {{{0x2298658, ...}, ...}, ...}, ...}, ...)
        github.com/elastic/terraform-provider-elasticstack/internal/kibana/data_view/create.go:43 +0x8e9
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0xc000186f20, {0x2293940, 0xc000225590}, 0xc0005472b0, 0xc000547250)
        github.com/hashicorp/terraform-plugin-framework@v1.4.2/internal/fwserver/server_createresource.go:101 +0x578
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0xc000547408?, {0x2293940, 0xc000225590}, 0xc0006899f0, 0xc000547408)
        github.com/hashicorp/terraform-plugin-framework@v1.4.2/internal/fwserver/server_applyresourcechange.go:57 +0x4a5
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0xc000186f20, {0x2293940?, 0xc000225470?}, 0xc000689950)
        github.com/hashicorp/terraform-plugin-framework@v1.4.2/internal/proto6server/server_applyresourcechange.go:55 +0x3ff
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ApplyResourceChange(0x2293978?, {0x2293940?, 0xc000225170?}, 0xc000689950)
        github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf6muxserver/mux_server_ApplyResourceChange.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc0002adea0, {0x2293940?, 0xc000224780?}, 0xc0001faa80)
        github.com/hashicorp/terraform-plugin-go@v0.19.1/tfprotov6/tf6server/server.go:857 +0x56a
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x2047ec0?, 0xc0002adea0}, {0x2293940, 0xc000224780}, 0xc0001a3100, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.19.1/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:467 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002381e0, {0x2293940, 0xc0002246c0}, {0x22992c0, 0xc000007520}, 0xc000223320, 0xc0003fdef0, 0x2d2f078, 0x0)
        google.golang.org/grpc@v1.59.0/server.go:1343 +0xe03
google.golang.org/grpc.(*Server).handleStream(0xc0002381e0, {0x22992c0, 0xc000007520}, 0xc000223320)
        google.golang.org/grpc@v1.59.0/server.go:1737 +0xc4c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.59.0/server.go:986 +0x86
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 7
        google.golang.org/grpc@v1.59.0/server.go:997 +0x145

Error: The terraform-provider-elasticstack_v0.11.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Versions (please complete the following information):**
 - OS: MacOS
 - Terraform Version 1.6.6
 - Provider version 0.11.0
 - Elasticsearch Version 7.17.13

**Comment by tobio** [comment]
```
2024-01-24T11:19:03.264+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: 2024/01/24 11:19:03 
2024-01-24T11:19:03.264+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: HTTP/2.0 200 OK
2024-01-24T11:19:03.264+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: Content-Type: application/json; charset=UTF-8
2024-01-24T11:19:03.264+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: Date: Wed, 24 Jan 2024 09:19:05 GMT
2024-01-24T11:19:03.264+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: Warning: 299 Elasticsearch-7.17.13-2b211dbb8bfdecaf7f5b44d356bdfe54b1050c13 "[types removal] Specifying types in document index requests is deprecated, use the typeless endpoints instead (/{index}/_doc/{id}, /{index}/_doc, or /{index}/_create/{id})."
2024-01-24T11:19:03.264+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: X-Cloud-Request-Id: WXJuMVSNS9KeSSwj_x4jdg
2024-01-24T11:19:03.264+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: X-Elastic-Product: Elasticsearch
2024-01-24T11:19:03.264+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: X-Found-Handling-Cluster: e7002f1200f24b5ab5343b51b6f6033e
2024-01-24T11:19:03.264+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: X-Found-Handling-Instance: instance-0000000008
2024-01-24T11:19:03.264+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0
2024-01-24T11:19:03.264+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.11.0: {"_index":"api","_type":"data_views","_id":"data_view","_version":19,"result":"updated","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":18,"_primary_term":1}
```

It looks like you've got the provider Kibana configuration pointing to an Elasticsearch endpoint, not a Kibana endpoint.

**Comment by Anri-Lombard** [comment]
It's so strange when I change my endpoints that I then get the error "Not Found" as well.

Since this is not the bug I suspected, I'll close this for now and do some more testing to figure this out.
